# Welcome to Jekyll!

# Website settings
title: "Lauren Ash"
description: "Lauren's website"
keywords: "UVM, amphibian, disease"
baseurl: "/"
url: "http://www.lvash.github.io"
# url: "http://127.0.0.1:4000"

# blog img path
img_path: ''

# author
author:
  name: 'Lauren'
  first_name: 'Ash'
  last_name: 'Lauren'
  email: 'lvash@uvm.edu'
  facebook_username: ''
  github_username: 'lvash'
  head_img: 'static/img/landing/Lauren.jpg'

# social link
jingyu:
  first_name: ''
  last_name: ''
  description: ''
  link: ''
  email: 'lvash@uvm.edu'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  skills: 'Skills'
  projects: 'Projects'
  blog: 'Blog'
  link: 'Contact'

# my projects
project:
  saplatform:
    name: 'Infectious Diseases'
    url: '/lvash/infectious_disease_project_dev'
    img: 'static/img/landing/saplatform.png'
  jalpc:
    name: 'Liatris novae-angliae'
    url: '/lvash/Liatris-novae-angliae'
    img: 'static/img/landing/rsser.png'


# blog index
index:
  home: 'Home'
  python: 'Python'
  linux: 'Linux'
  html: 'HTML'
  database: 'Database'
  mac: 'Mac'
  life: 'Life'

# donate
donate:
  wechat: ''
  alipay: ''

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: 
  public_key: 

# share
bshare:
  uuid: 

# baidu analytics
ba:
  uuid: 

# google analytics
ga:
  id: 

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
